---
- name: Add Jenkins repository
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: '0644'

- name: Import Jenkins repository key
  ansible.builtin.rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

- name: Install Jenkins
  ansible.builtin.dnf:
    name: jenkins
    state: present
    update_cache: true

- name: Enable and start Jenkins
  ansible.builtin.systemd:
    name: jenkins
    enabled: true
    state: started
