apiVersion: apps/v1
kind: Deployment
metadata:
  name: roadmap-service
  namespace: ivolve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roadmap-service
  template:
    metadata:
      labels:
        app: roadmap-service
    spec:
      containers:
        - name: roadmap-service
          image: ivolve-roadmap-service:latest
          ports:
            - containerPort: 8080
