apiVersion: v1
kind: ConfigMap
metadata:
  name: ivolve-config
  namespace: ivolve
data:
  DB_NAME: "ivolve"
  DB_PORT: "3306"
  AUTH_SERVICE_URL: "http://auth-service:5000"
  ROADMAP_SERVICE_URL: "http://roadmap-service:8080"
