apiVersion: v1
kind: Secret
metadata:
  name: ivolve-secret
  namespace: ivolve
type: Opaque
data:
  DB_ROOT_PASSWORD: cm9vdHBhc3M=
  DB_USER: eW91c3NlZg==
  DB_PASSWORD: eW91c3NlZkAxMjM=
  SESSION_SECRET: Y2hhbmdlLW1lLWluLWs4cw==
