apiVersion: v1
kind: Secret
metadata:
  name: ivolve-secret
  namespace: ivolve
type: Opaque
stringData:
  DB_ROOT_PASSWORD: "rootpass"
  DB_USER: "youssef"
  DB_PASSWORD: "youssef@123"
  SESSION_SECRET: "change-me-in-k8s"
